import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";

const infrastructure = await import("../../packages/infrastructure/dist/index.js");
const application = await import("../../packages/application/dist/index.js");

test("ollama embedding provider returns embeddings from the configured local model API", async () => {
  const provider = new infrastructure.OllamaEmbeddingProvider({
    baseUrl: "http://127.0.0.1:11434",
    model: "embeddinggemma",
    fetchImplementation: async (url, init) => {
      assert.match(String(url), /\/api\/embed$/);
      const payload = JSON.parse(String(init.body));
      assert.equal(payload.model, "embeddinggemma");
      return new Response(
        JSON.stringify({
          embeddings: [
            [0.1, 0.2, 0.3],
            [0.3, 0.2, 0.1]
          ]
        }),
        {
          status: 200,
          headers: { "content-type": "application/json" }
        }
      );
    }
  });

  const embeddings = await provider.embedTexts(["alpha", "beta"]);
  assert.deepEqual(embeddings, [
    [0.1, 0.2, 0.3],
    [0.3, 0.2, 0.1]
  ]);
});

test("ollama local reasoning provider parses structured reasoning outputs", async () => {
  const responses = [
    { response: JSON.stringify({ intent: "debugging" }) },
    { response: JSON.stringify({ answerability: "partial" }) },
    { response: JSON.stringify({ summary: "Local context is partial." }) }
  ];

  const provider = new infrastructure.OllamaLocalReasoningProvider({
    baseUrl: "http://127.0.0.1:11434",
    model: "qwen3",
    fetchImplementation: async () =>
      new Response(JSON.stringify(responses.shift()), {
        status: 200,
        headers: { "content-type": "application/json" }
      })
  });

  const intent = await provider.classifyIntent("Why is the writer failing to promote notes?");
  assert.equal(intent, "debugging");

  const answerability = await provider.assessAnswerability({
    query: "Why is the writer failing to promote notes?",
    intent,
    candidates: []
  });
  assert.equal(answerability, "partial");

  const uncertainty = await provider.summarizeUncertainty("promotion failure", ["limited evidence"]);
  assert.equal(uncertainty, "Local context is partial.");
});

test("staging draft service uses the drafting provider output before deterministic validation", async (t) => {
  const root = await mkdtemp(path.join(os.tmpdir(), "mab-drafting-"));
  const sqlitePath = path.join(root, "state", "multi-agent-brain.sqlite");
  const metadataControlStore = new infrastructure.SqliteMetadataControlStore(sqlitePath);

  t.after(async () => {
    metadataControlStore.close();
    await rm(root, { recursive: true, force: true });
  });

  const stagingRepository = new infrastructure.FileSystemStagingNoteRepository(
    path.join(root, "vault", "staging")
  );
  const noteValidationService = new application.NoteValidationService();
  const stagingDraftService = new application.StagingDraftService(
    stagingRepository,
    metadataControlStore,
    noteValidationService,
    {
      providerId: "fake-local-drafting",
      async draftStructuredNote(request) {
        return {
          draftNoteId: request.frontmatterOverrides?.noteId ?? randomUUID(),
          lifecycleState: "draft",
          draftPath: "",
          frontmatter: {
            noteId: request.frontmatterOverrides?.noteId ?? randomUUID(),
            title: request.title,
            project: "multi-agent-brain",
            type: request.noteType,
            status: "draft",
            updated: new Date().toISOString().slice(0, 10),
            summary: request.sourcePrompt,
            tags: ["project/multi-agent-brain", "status/draft"],
            scope: "staging",
            corpusId: request.targetCorpus,
            currentState: false
          },
          body: [
            "## Context",
            "",
            "Generated by local drafting.",
            "",
            "## Decision",
            "",
            "Use the drafting provider when available.",
            "",
            "## Rationale",
            "",
            "This keeps the service transport-agnostic.",
            "",
            "## Consequences",
            "",
            "Validation still governs the output."
          ].join("\n"),
          warnings: ["used local drafting provider"]
        };
      }
    }
  );

  const result = await stagingDraftService.createDraft({
    actor: {
      actorId: "writer-test",
      actorRole: "writer",
      transport: "internal",
      source: "test-suite",
      requestId: randomUUID(),
      initiatedAt: new Date().toISOString()
    },
    targetCorpus: "context_brain",
    noteType: "decision",
    title: "Local Drafted Decision",
    sourcePrompt: "Create a promoted drafting policy.",
    supportingSources: []
  });

  assert.equal(result.ok, true);
  assert.match(result.data.body, /Generated by local drafting/);
  assert.ok(result.data.warnings.includes("used local drafting provider"));
});
