export const COMMANDS = [
  "list-tools",
  "describe",
  "run",
  "workspace tree-lite",
  "workspace file-inventory",
  "text smart-search",
  "text chunk-file",
  "text log-summary",
  "documents extract-headings",
  "documents extract-links",
  "documents extract-text",
  "documents doc-check",
  "data csv-profile",
  "media media-info",
  "project diff-summary",
  "project command-index",
  "config config-map",
  "maintenance cleanup-candidates",
  "file-inventory",
  "tree-lite",
  "smart-search",
  "chunk-file",
  "log-summary",
  "diff-summary",
  "command-index",
  "config-map",
  "csv-profile",
  "extract-headings",
  "doc-check",
  "cleanup-candidates",
  "extract-text",
  "extract-links",
  "media-info"
];
